name: Covasim CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: ['3.8']
    name: Run tests
    steps:
      - name: Set repo owner env variable
        shell: python
        run: print("::set-env name=GITHUB_OWNER::{}".format('${{github.repository}}'.split('/')[0]))
      - name: Set PYTHONPATH
        run: |
          mkdir -p $HOME/.cache/site-packages
          echo "::set-env name=PYTHONPATH::$HOME/.cache/site-packages"
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Covasim
        run: |
          python setup.py develop --install-dir ~/.cache/site-packages
          pip install pytest
      - name: Run integration tests
        working-directory: ./tests
        run: pytest test*.py --durations=0 # Run actual tests
      - name: Run unit tests
        working-directory: ./tests/unittests
        run: pytest test*.py --durations=0 # Run actual tests
