name: Covasim CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: ['3.9']
    name: Run tests
    steps:
      - name: Set repo owner env variable
        shell: python
        run: print("::set-env name=GITHUB_OWNER::{}".format('${{github.repository}}'.split('/')[0]))
      - name: Set PYTHONPATH
        run: |
          mkdir -p $HOME/.cache/site-packages${{ matrix.python-version }}
          echo "::set-env name=PYTHONPATH::$HOME/.cache/site-packages${{ matrix.python-version }}"
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/ # This path is specific to Ubuntu
          key: packages-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }} # Look to see if there is a cache hit for the corresponding requirements file
          restore-keys: |
            packages-${{ runner.os }}-${{ matrix.python-version }}- # Pip install first will make setup.py much faster and the cache will make pip install fast
      - name: Install Covasim
        # run: python setup.py develop --install-dir ~/.cache/site-packages
        run: python setup.py develop --install-dir ~/.cache/site-packages${{ matrix.python-version }}
      - name: Run integration tests
        working-directory: ./tests
        run: |
          pip install pytest
          pytest test*.py --durations=0 # Run actual tests
      - name: Run unit tests
        working-directory: ./tests/unittests
        run: pytest test*.py --durations=0 # Run actual tests
